version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...

      - yarn

  build:
    commands:
      # - echo Testing...

      # - yarn test

      - echo Building...

      - pm2 restart portfolio
artifacts:
  files:
    - "**/*"
  discart-paths: no
  base-directory: dist
